# Haven't fully tested this yet
# will need to change image name in compose file if on boot2docker
FROM elasticsearch:5.2
MAINTAINER DavyJ0nes <davy.jones@me.com>
ENV UPDATED_ON 18-02-2017

COPY ./config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
